### ISSUE TITLE
'No releases data found' warning.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/project_browser#19]
Do we know why for some modules we get a warning like this one for Simplenews?
![project browser - www revivalwoodbridge org uk 2015-06-03 15-05-08](https://cloud.githubusercontent.com/assets/10559274/7963347/27d8445c-0a0a-11e5-86b1-f6e76a7f2b61.png)

For most projects it seems that project_browser is working well.

**Comment by docwilmot** [comment]
Its a fault of project module on backdropcms.org. project_browser gets release info from calling a url like this: https://updates.backdropcms.org/release-history/hopscotch/1.x note that https://updates.backdropcms.org/release-history/simplenews/1.x doesnt work.

I can see that simplenews has a packaging error in its release (wrong release tag format). So it seems that its formed a project node, but no release node. That shouldnt happen.

Tagging @quicksketch.

**Comment by quicksketch** [comment]
> So it seems that its formed a project node, but no release node. That shouldnt happen.

I agree this shouldn't happen, we've got an issue with the packager clearly. Thanks for opening https://github.com/backdrop-ops/backdropcms.org/issues/69.

Separately from the packager problem, I do think that we should somehow accommodate for projects that do not have any official releases. Project browser should check that only projects that have releases are shown for installation. Longer-term, we'll also need to only show projects that are compatible with the current version of Backdrop CMS with which the user is doing the browsing. So a project very well may have releases for Backdrop 1.x but not 2.x. We don't want to show users releases that wouldn't be compatible, or perhaps we would show that the projects exist but that they are not yet compatible.

**Comment by docwilmot** [comment]
> I do think that we should somehow accommodate for projects that do not have any official releases.

Those have GitHub; I think the official listing should stick to releases. 

> Project browser should check that only projects that have releases are shown for installation

Agreed, will look into that,

> We don't want to show users releases that wouldn't be compatible

Good point, currently you can filter by major version, which is useful if youre planning an upgrade, just to browse. But I'll check that install is blocked.
