### ISSUE TITLE
Add to install queue problem

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/project_browser#2]
When you select 'Add to install queue' or 'Remove from install queue' the Install Queue listing in the right-hand column is not being updated until the page is refreshed, as it is in the Drupal version. Perhaps this is an Ajax problem?

**Comment by Graham-72** [comment]
@wildkatana - I would be very grateful for your suggestions on this one. In the Backdrop version we have ported so far we are not getting the same behaviour as in your Drupal version. The module or theme is being added to the install queue, but the install queue list is not being refreshed, nor is the link ''Add to install queue" being changed to "Remove from install queue" until the whole page is refreshed. 

I'm afraid I am no expert on Javascript but I suspect it may be something in our Backdrop version of ajax.js, or alternatively something to do with the different theming of blocks and pages in Backdrop. If you have any suggestion as to where I might look to solve this one I would be most grateful.

**Comment by Drupaldise** [comment]
I will have a look at this in the next days

**Comment by Drupaldise** [comment]
This small change will fix the problem https://github.com/backdrop-contrib/project_browser/commit/46bdefeaf0b7ced2e81b4277adb2019f00c3a33d

**Comment by Graham-72** [comment]
:+1:  @Drupaldise - thanks.
