### ISSUE TITLE
Project Browser can sort by author, but all authors are Backdrop Contrib.

### ISSUE THREAD

**Issue by sentaidigital** [backdrop-contrib/project_browser#25]
Project Browser will happily sort by author, but all of the authors are "Backdrop Contrib," apparently pulling the project group name as the module author.  This, of course, makes sorting by author quite pointless.

The authors are not shown on the listing view, but are shown in the detail overlay.  (see attached image.)

Either the actual authors need to be properly sourced or the sort option and displayed field should be removed.

![project_browser-author-field](https://cloud.githubusercontent.com/assets/481531/14923941/034392d2-0e0e-11e6-99c4-2e6ef29b963e.png)

**Comment by docwilmot** [comment]
Hello @sentaidigital, project browser is set for merging into core in the next release, so essentially I have abandoned work on this contrib for a while now while working on the merge. The issues you raised have been addressed though, and should be fixed in core.

**Comment by sentaidigital** [comment]
Hmm... is there some way we can mark this as Obsolete or In-Core or just take it down?

**Comment by docwilmot** [comment]
I think it still functions reasonably so I'd prefer to leave it up in contrib as it is until it actually is merged in. The merge update script should account for previous installs. Then we'll happily mark this obsolete.

**Comment by sentaidigital** [comment]
How do we make it obvious that this is not the right version to file issues against?  Maybe disable the issue queue on this repo, or change the description to say, "coming soon to core in 1.4" and update the README.md?

**Comment by docwilmot** [comment]
Added a notice to README, thanks
