### ISSUE TITLE
template error for $classes

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/project_browser#3]
In project-browser-block.tpl.php
`<div class="<?php print $classes; ?>">` should now be `<div class="<?php print implode(' ', $classes); ?>">`
I get an error otherwise. 
Looking forward to getting this browser working!

**Comment by Graham-72** [comment]
Thanks @docwilmot I have added this change.
Things are progressing. I am impressed by how much is ready-made for us in these modules.
It's a bit risky to say this but I think I can see daylight ahead!
