### ISSUE TITLE
json feed from project_browser_server

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/project_browser#4]
@docwilmot - I am trying to find a way of dealing with this in Backdrop and would appreciate any thoughts you may have.

At the moment, when the default_server URL is changed appropriately, project-browser gets its test data by using the URL
http://www.mytestsite.net/project_browser/server/query/module/7?version=1&type=module&order_by=score&sort=desc&requested=10&page=0&method=query

This calls the following function within project_browser_server.module - line 76

```
/**
 * Return some JSON or JSONP to the page.
 */
function _project_browser_server_return($results) {
  // JSONP
  if (!empty($_GET['callback'])) {
    // @todo msie9 might break with this content-type.
    // @see http://stackoverflow.com/questions/111302/best-content-type-to-serve-jsonp/111306#111306
    backdrop_add_http_header('Content-Type', 'application/javascript; charset=utf-8');
    print $_GET['callback'] . '(' . backdrop_json_encode($results) . ');';
  }
  else {
    backdrop_add_http_header('Content-Type', 'application/json; charset=utf-8');
    print backdrop_json_encode($results);
  }
}
```

In Drupal this produces the json output and nothing else.
In Backdrop it produces the json output followed by the html for a page.

I am wondering how to suppress the html which I assume is added by the layout system. Is it possible to bypass the layout system for specific paths? I would like to be able to choose 'no layout' where there is a choice of 1 column etc.

Any suggestions would be much appreciated. My other inclination is to build a simple non-Backdrop server page just to generate the test data in json form so we can proceed with testing with Backdrop rather than Drupal data. 

I have just had a thought - as a temporary expedient I can use an installation of project_browser_server on a Drupal site and just modify the test data in pbs_example.module to get the right json data. But we will need it on Backdrop for the final system.

**Comment by kerasai** [comment]
I've noticed this as well. Take a look at other JSON type callbacks,
user/autocomplete for instance. Basically just a backdrop_json_output() and
an early exit.

It'd be nice to have a cleaner way, a delivery callback perhaps, but this
seems to work.

Are you at Drupalcon? I'm here, can talk through some issues if you like.

**Comment by Graham-72** [comment]
Thanks @kerasai I will do this.

Unfortunately I am not at Drupalcon - I'm in UK.

**Comment by Graham-72** [comment]
:+1: Solves the problem. I will now create a PR.
