### ISSUE TITLE
Project Browser progress

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/project_browser#6]
Progress so far:-
1. Porting to Backdrop is complete, with the exception of a suspected javascript problem causing the issue reported in https://github.com/backdrop-contrib/project_browser/issues/2
2. The json test data is now being successfully provided by module project_browser-server running in Backdrop, and I have added data about 3 themes and 3 modules and these are successfully displayed. 
   Pull requests https://github.com/backdrop-contrib/project_browser/pull/5, https://github.com/backdrop-contrib/project_browser_server/pull/2 and https://github.com/backdrop-contrib/project_browser_server/pull/1 relate to this.
3. We need further consideration of exactly what information we should display in these listings.
4. Once Issue #2 has been solved, the next step will, I think, be to consider linking project_browser_server with project. Project_browser already includes code from the update module so hopefully not much will need to be done to this stage.
5. Images are attractive in listings - perhaps we need to ask module providers to include an image or logo in their repositories? Some already do.

Comments and suggestions are most welcome.

**Comment by docwilmot** [comment]
Nice to see good progress!
Does project browser actually download and install modules?

**Comment by Graham-72** [comment]
I believe it will do once we feed it with the right data i.e. the URLs for the download files, the same as needed for updates.

**Comment by docwilmot** [comment]
I'm confused. You already added the right data in https://github.com/backdrop-contrib/project_browser_server/pull/2.

**Comment by Graham-72** [comment]
Sorry for causing confusion. The data I added was specifically for a handful of Backdrop contributed modules so that they show up in the listings, rather than the Drupal ones. One item for each is the link for the download file, and I have used the link for 'releases' as a quick stop-gap. Once I have checked this out, I expect I will need to enter the link for the zip of the latest release. But this is only for testing. It will be replaced by the dynamic data available from 'project' (well, that's my assumption at the moment).

As soon as I get an answer to the javascript problem that I think we have, I will get the right download URLs in the test data so we can check this out.

**Comment by docwilmot** [comment]
:smile: I think our thoughts are running parallel and not crossing. One more try:

If you notice, the feed from drupal project browser server doesnt contain a download link. To actually fetch projects **the server is not necessary!** If you give project_browser the machine name of the project, it fetches the project using update module. 

Last I checked (yesterday) Backdrops update module already can fetch projects from GitHub. 

So once you've given project_browser a project name (`'name' => 'views_slideshow',` or `'name' => 'colorbox'` it should work! If it doesnt, you dont have to wait for the server, or for project module, youve got to figure out why its not downloading.

Hope you get my point?

**Comment by Graham-72** [comment]
> If you notice, the feed from drupal project browser server doesnt contain a download link.

That's interesting!
The feed from his server at https://www.moneyscripts.net/project_browser/server includes this (for the Views module)

"project url":"https:\/\/www.drupal.org\/project\/views",

"project status url":"http:\/\/updates.drupal.org\/release-history\/views\/7.x",

"last updated":"1430320981",

So I have been assuming that this is the information needed by project_browser. But maybe there is a way it can do it by asking somewhere (where?) by module name for the latest downloads. From what you say it sounds as though 'update' is the place.

**Comment by docwilmot** [comment]
"project status url" it seems fetches an xml file with all release data; but I dont see where this is used in the code. project_browser.inc, line 635 uses this to get release data:

```
function project_browser_get_project_release_data($project) {
  $project['project_type'] = $project['type'];

  // Build the releases cache for this project
  module_load_include('inc', 'update', 'update.fetch');
  if (_update_process_fetch_task($project)) {
    $data = _update_cache_get('available_releases::' . $project['name']);
...
```

and `_update_process_fetch_task()` is an update.module function which I assume does its job since we can download from GitHub.

Of course this is all assumptions, since I havent tried.

**Comment by Graham-72** [comment]
Thanks to hard work by @docwilmot we have come a long way and this issue is superseded by #10
