### ISSUE TITLE
Getting information from Github on Projects

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/project_browser#8]
@docwilmot - it seems that project_browser would be able to get a detailed list as json data of all the contributed projects from url https://api.github.com/users/backdrop-contrib/repos

From this could be extracted those with releases, and then for each individual project the details are available from, for example, https://api.github.com/repos/backdrop-contrib/ckeditor/releases , and this contains the url for downloading the package.

This being so, there should be no need for project_browser_server.

I have written the above partly as a record for myself, as I proceed now with adapting project_browser to do this. 

@quicksketch - I see a need for a standard file name for an image file for each contributed module, e.g. projectimage.jpg in the main directory for the project. Having an image in the project listing may not be essential but does make it more attractive. Having a standard file name would make it easy for project_browser to reference it.

**Comment by docwilmot** [comment]
> e.g. projectimage.jpg in the main directory for the project 

Or in the .info file? https://github.com/backdrop-ops/backdropcms.org/issues/8#issuecomment-94890884 and https://github.com/backdrop/backdrop-issues/issues/37 and https://github.com/backdrop/backdrop-issues/issues/119

> This being so, there should be no need for project_browser_server

There would likely be still a need for the server I suspect, except if GitHub API can do the queries we need? But at least we may not need the server to get project_browser actually working if we can feed it info from another (temporary) source.

**Comment by quicksketch** [comment]
I think we'll probably still need a project browser to cut down on client-side processing. Hitting GitHub for a listing of projects, then parsing .info files (and optionally checking for a preview image), would be a lot of processing for the client-side. I also think we may need the project server to facilitate adequate searching abilities. Searching should have some decent relevancy and potentially the ability to sort by project popularity (active installs).

**Comment by klonos** [comment]
> I see a need for a standard file name for an image file for each contributed module, e.g. projectimage.jpg in the main directory for the project. Having an image in the project listing may not be essential but does make it more attractive. Having a standard file name would make it easy for project_browser to reference it.

I realize that using a single image is a pattern we are used to from the themes listing page, but for projects it is often required to have a series of images - not only one. For example, showing a before/after effect or the admin/edit page and then also the user-facing result. You can see this happening for quite a few projects in d.org ([Content Menu](https://www.drupal.org/project/content_menu)) and also in [addons.mozilla.org](https://addons.mozilla.org/) or the google plugin browser in chrome that show these images as a slideshow.

I propose supporting projectname_1.jpg, projectname_2.jpg,projectname_3.jpg etc as well.

**Comment by Graham-72** [comment]
Thanks for your responses. I will continue with project_browser_server, though rather slowly this week because I am holiday.

> the ability to sort by project popularity (active installs).

I can see download_count in the github data but where will we find data on active installs? Presumably this comes from sites checking somewhere for updates, and hence known to be active?

**Comment by quicksketch** [comment]
> I can see download_count in the github data but where will we find data on active installs? Presumably this comes from sites checking somewhere for updates, and hence known to be active?

Yeah, we'll have this information on BackdropCMS.org, as sites that have update.module enabled also report which modules they have enabled on their site, so the only place we'll be able to get this information would be the Project server. We already have this in place and statistics can start to be collected, but we haven't enabled the public responses yet.

**Comment by docwilmot** [comment]
> I propose supporting projectname_1.jpg, projectname_2.jpg,projectname_3.jpg etc as well.

Or:

```
screenshot[] = screenshots/projectname_1.jpg
screenshot[] = screenshots/projectname_2.jpg
screenshot[] = screenshots/projectname_big.jpg
screenshot[] = screenshots/imgname_whatever.jpg
```

**Comment by quicksketch** [comment]
I like the idea of screenshots in the .info file, as hopefully it would encourage developers to use them for that purpose. In some communities (Joomla in particular) it's very common to have a dedicated logo or even a box of software (yak) displayed on the project page. However, from a functional standpoint, a screenshot tells much more than a logo, and would be suitable for themes and modules.

**Comment by Graham-72** [comment]
@quicksketch - another thing, I cannot see anything in the GitHub records for backdrop-contrib projects that indicates whether they are modules, themes or anything else. Is there something there? If not, are there plans for this to be available? I am hoping not to have to enter it manually per project for project_browser_server to use.

**Comment by docwilmot** [comment]
See comment https://github.com/backdrop/backdrop-issues/issues/870#issuecomment-101054892

Project.module, installed on B.org, is already creating records of all GitHub projects, as you know. The data that project_browser_server needs will come from project.module on B.org, not directly from GitHub. project_browser_server will be installed on B.org.

**Comment by quicksketch** [comment]
> I cannot see anything in the GitHub records for backdrop-contrib projects that indicates whether they are modules, themes or anything else. Is there something there? If not, are there plans for this to be available?

Yeah, we encountered this as well. To keep track of which projects are modules, layouts, or themes, we now encourage/require projects to include a `type = module` (or theme/layout) line in the .info file. If you don't include a type, the packager on BackdropCMS.org will attach a PACKAGING_ERROR_LOG.txt file to your project release on GitHub.

So as @docwilmot said, we're already tracking this information on BackdropCMS.org, so pulling the project data from there is the most likely solution.

**Comment by Graham-72** [comment]
@quicksketch  Thanks, I had forgotten that we are now adding type = module. On a more general matter, several days ago you commented in https://github.com/backdrop/backdrop-issues/issues/870 -

> Really you don't need an installation of BackdropCMS.org, for starters you could just install https://github.com/backdrop-contrib/project on the local installation that will act as the server.

Maybe I am doing something wrong, but I have tried installing project, expecting that it would automatically collect project information and build a set of content type 'project', but it seems to require manual addition of these, one at a time. So I am wondering what I am doing wrong, or are my expectations wrong? Is 'project' working on backdropcms.org?

As an alternative temporary arrangement I have been working towards an addition for project_browser_server that replaces its inbuilt 'project browser server example' module with one that collects data from github rather than use the sample data within it.

**Comment by quicksketch** [comment]
> Maybe I am doing something wrong, but I have tried installing project, expecting that it would automatically collect project information and build a set of content type 'project', but it seems to require manual addition of these, one at a time.

When you install project.module and project_release.module, it should automatically create project and project_release node types. So the types are created automatically for you. However, after that, you need to create the individual projects and releases manually. BackdropCMS.org receives GitHub webhook requests as releases are made, but these webhooks had to be manually configured (there's information on how this was done in the README.md in the project_github submodule).

To make things easier, I'd definitely be up for making a database dump and config export for you to use, then you can just clone the entire installation of BackdropCMS.org from https://github.com/backdrop-ops/backdropcms.org.

**Comment by Graham-72** [comment]
> BackdropCMS.org receives GitHub webhook requests as releases are made, but these webhooks had to be manually configured (there's information on how this was done in the README.md in the project_github submodule).

Am I correct in thinking that I would need to set up a webhook on repo backdrop-contrib? I don't think I have the permission needed to do this, do I?

**Comment by quicksketch** [comment]
> Am I correct in thinking that I would need to set up a webhook on repo backdrop-contrib? I don't think I have the permission needed to do this, do I?

You could set up a webhook on any repository, it doesn't have to be in the backdrop-contrib group. I'd been using a module in my own personal account: https://github.com/quicksketch/hooktest/

But all together, you really don't need to be receiving web hooks at all. You can just manually create the project nodes and release nodes. The only thing the GitHub integration does is synchronize the information into user-editable fields.

**Comment by Graham-72** [comment]
> You could set up a webhook on any repository, it doesn't have to be in the backdrop-contrib group.

@quicksketch I was following a train of thought that I might use the github APIs to get all the project data, but came up against the github limit of 60 uses per hour unless authenticated.

Because of the excellent progress by @docwilmot I have put this to one side at the moment, but just for the record, in trying to set up a web hook I found that after creating a 'Personal access token' on github I was unable to complete the github instructions: 

> To set up a repository webhook on GitHub, head over to the Settings page of your repository, and click on Webhooks & services. After that, click on Add webhook.

This was from https://developer.github.com/webhooks/creating/

But I don't get to see the settings page for the repo backdrop-contrib. I was just hoping to find a short cut way of getting all the project data, then keeping it updated as projects are added. But it is not a priority.

Or possibly, and quite likely, I have misunderstood the github process for setting up a webhook.

**Comment by quicksketch** [comment]
> But I don't get to see the settings page for the repo backdrop-contrib. I was just hoping to find a short cut way of getting all the project data, then keeping it updated as projects are added.

Yeah you can't access the webhook settings for projects within backdrop-contrib. What I've been doing for my testing is setting up a stand-alone repository and doing all the testing against that one project. In order to adequately test packaging, you have to be able to push changes back to the testing repository. For obvious reasons we don't want in-development code to modify the backdrop-contrib projects directly.
